# Generated by Django 3.1 on 2020-12-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0002_auto_20201214_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('EL', 'élève'), ('PR', 'professeur'), ('AS', 'assistant de laboratoire'), ('VS', 'Vie scolaire'), ('CP', 'C.P.E.'), ('AU', 'Autre')], default='AU', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('EC', 'Eco-Ambassadeur'), ('HO', "Eco-Ambassadeur d'Honneur")], default='EC', max_length=2),
        ),
    ]
