# Generated by Django 3.1 on 2020-12-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0004_user_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
