# Generated by Django 3.1 on 2021-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_article',
            name='user',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='comment_idea',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
