# Generated by Django 3.1 on 2021-02-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0007_auto_20210223_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_article',
            name='user_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comment_idea',
            name='user_email',
            field=models.EmailField(default='exemple@exemple.com', max_length=254),
            preserve_default=False,
        ),
    ]
