# Generated by Django 3.1 on 2021-02-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0008_auto_20210224_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_article',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
