# Generated by Django 3.1 on 2021-02-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0009_auto_20210224_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='URL_video',
            field=models.URLField(default='https://www.westernheights.k12.ok.us/wp-content/uploads/2020/01/No-Photo-Available.jpg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='URL_video',
            field=models.URLField(default='https://www.westernheights.k12.ok.us/wp-content/uploads/2020/01/No-Photo-Available.jpg'),
        ),
    ]
