# Generated by Django 3.1 on 2021-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0011_auto_20210225_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='URL_video',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='URL_video',
            field=models.URLField(blank=True),
        ),
    ]
