# Generated by Django 3.1 on 2021-02-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0012_auto_20210225_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecow.idea')),
            ],
        ),
    ]
