# Generated by Django 3.1 on 2021-04-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0018_auto_20210406_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='URL_image',
            field=models.URLField(default='https://static.thenounproject.com/png/1554490-200.png'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='URL_image',
            field=models.URLField(default='https://static.thenounproject.com/png/1554490-200.png'),
        ),
        migrations.AlterField(
            model_name='product',
            name='URL_image',
            field=models.URLField(default='https://static.thenounproject.com/png/1554490-200.png'),
        ),
        migrations.AlterField(
            model_name='project',
            name='URL_image',
            field=models.URLField(default='https://static.thenounproject.com/png/1554490-200.png'),
        ),
    ]
