# Generated by Django 3.1 on 2021-04-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0019_auto_20210406_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='URL_video',
            field=models.URLField(blank=True),
        ),
    ]
