# Generated by Django 3.1 on 2021-04-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0023_image_field_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='FIELD_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='URL_image',
            field=models.URLField(blank=True),
        ),
    ]
