# Generated by Django 3.1 on 2021-04-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecow', '0024_auto_20210407_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='URL_image',
        ),
    ]
